#===============================================================================
#
#          FILE:  1568346_20220619.yml
#
#         USAGE:  - See https://docs.github.com/en/actions
#                       /learn-github-actions/understanding-github-actions
#                 - Add .github/workflows/1568346_20220619.yml to repository.
#                   This will not work for forks
#
#   DESCRIPTION:  ---
#
#       OPTIONS:  ---
#
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Emerson Rocha <rocha[at]ieee.org>
#       COMPANY:  EticaAI
#       LICENSE:  Public Domain dedication or Zero-Clause BSD
#                 SPDX-License-Identifier: Unlicense OR 0BSD
#       VERSION:  v1.0
#       CREATED:  2022-06-19 17:29 UTC started.
#      REVISION:  ---
#===============================================================================
# SPDX-License-Identifier: Unlicense OR 0BSD

# @TODO eventually make it run weekly
# @TODO organize log messages when running on github actions to allow be grouped
#       docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions
# @TODO test gh (github cli). Maybe tehre is less verbose way to sync the
#       repositories than editing 'git commit' directly.
#       docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows
name: "aN1568346_20220619"

on:
  push:
    branches:
      - main

env:
  # Fix: 'tput: No value for $TERM and no -T specified'
  TERM: xterm

# defaults:
#   run:
#     working-directory: ./officina

jobs:
  "a1568346_20220619":
    name: a1568346_20220619
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      #### Low level ssh-agent _________________________________________________
      # # @see https://github.com/marketplace/actions/webfactory-ssh-agent
      # # REASONING: this is not necessary for read-only requests to public
      # #            repositories, but for use GitHub Actions runner, we need
      # #            something far more dynamic than write YAML for every
      # #            repository we would create with shell scripting
      # - name: ID_ED25519__GITHUBRUNNER2022
      #   uses: webfactory/ssh-agent@v0.5.4
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY__ID_ED25519__GITHUBRUNNER2022 }}

      # - run: ssh -T git@github.com
      #   continue-on-error: true

      #### Fetch data __________________________________________________________

      - name: apothēca [MDCIII/1568346_20220619]
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # - name: EticaAI/lexicographi-sine-finibus
      #   uses: actions/checkout@v3
      #   with:
      #     repository: EticaAI/lexicographi-sine-finibus
      #     path: officina/999999/3133368/lexicographi-sine-finibus

      - name: EticaAI/lsf-cache
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          repository: EticaAI/lsf-cache
          path: officina/999999/3133368/lsf-cache
          fetch-depth: "1"

      - name: "[EticaAI/lsf-cache/1603/1/1603 -> apothēca]"
        run: >
          rsync --verbose --human-readable --checksum --recursive
          --prune-empty-dirs
          --include "*/"
          --include="*.ttl" --include="*.owl"  --include="*.csv"
          --exclude=".gitkeep"
          --exclude="*"
          officina/999999/3133368/lsf-cache/1603/1/1603/
          officina/1603/1/1603
        continue-on-error: true

      # - run: mkdir -p officina/1603/16/24

      - name: MDCIII/1603_16_24
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          repository: MDCIII/1603_16_24
          path: officina/999999/3133368/1603_16_24
          fetch-depth: "1"

      - name: "[MDCIII/1603_16_24/1603/16/24/ -> apothēca]"
        run: >
          rsync --verbose --human-readable --checksum --recursive
          --prune-empty-dirs
          --include "*/"
          --include="*.ttl" --include="*.owl"  --include="*.csv"
          --exclude=".gitkeep"
          --exclude="*"
          officina/999999/3133368/1603_16_24/1603/16/24/
          officina/1603/16/24
        continue-on-error: true

      # - name: MDCIII/1603_16_24 -> apothēca
      #   uses: actions/checkout@v3
      #   continue-on-error: true
      #   with:
      #     repository: MDCIII/1603_16_24
      #     path: officina/999999/3133368/1603_16_24

      # - name: MDCIII/999999_1603_16
      #   uses: actions/checkout@v3
      #   continue-on-error: true
      #   with:
      #     repository: MDCIII/999999_1603_16
      #     path: officina/999999/3133368/999999_1603_16

      # Debug part, remove later, START
      - run: pwd
      - run: find * -type f
        continue-on-error: true
      - run: pwd
      - run: git status
        continue-on-error: true
      # # Debug part, remove later, END

      # - name: "Merge 999999 [MDCIII/999999_1603_16 -> EticaAI/lexicographi-sine-finibus]"
      #   run: >
      #     rsync --verbose --human-readable --checksum --recursive
      #     999999/3133368/999999_1603_16/999999/
      #     999999/3133368/lexicographi-sine-finibus/officina/999999
      #   continue-on-error: true

      # - name: "Merge 999999 [MDCIII/999999_1603_16 -> EticaAI/lexicographi-sine-finibus]"
      #   run: rsync --dry-run --verbose --human-readable --checksum --recursive officina/999999/3133368/999999_1603_16/999999/ officina/999999/3133368/lexicographi-sine-finibus/officina/999999
      #   continue-on-error: true

      # # Debug part, remove later, START
      # - run: pwd
      # - run: ls -lha
      # - run: ls -lha 999999/
      #   continue-on-error: true
      # - run: ls -lha 999999/3133368/
      #   continue-on-error: true
      # - run: find * -type f
      #   continue-on-error: true
      # # Debug part, remove later, END

      # ### Symlinks
      # - name: officina/1603
      #   run: >
      #     ln --relative --symbolic
      #     999999/3133368/lexicographi-sine-finibus/officina/1603
      #     1603
      #   continue-on-error: true

      # - name: officina/999999/1603
      #   run: >
      #     ln --relative --symbolic
      #     999999/3133368/lexicographi-sine-finibus/officina/999999/1603
      #     999999/1603
      #   continue-on-error: true

      # - name: officina/999999999/0
      #   run: >
      #     ln --relative --symbolic
      #     999999/3133368/lexicographi-sine-finibus/officina/999999999/0
      #     999999999/0
      #   continue-on-error: true

      # # 1603_1_99 is not stored with main repository, but is required by
      # # scripts that generate Codex. For now we're simply downloading
      # # from the older EticaAI/lsf-cache/ repository
      # - name: "Temporary fix [1603/1/99/1603_1_99.no1.tm.hxl.csv]"
      #   run: >
      #     curl --output 1603/1/99/1603_1_99.no1.tm.hxl.csv
      #     https://raw.githubusercontent.com/EticaAI/lsf-cache/main/1603/1/99/1603_1_99.no1.tm.hxl.csv
      #   continue-on-error: true

      # - name: "Temporary fix [999999/1603/45/16/1603_45_16.index.hxl.csv]"
      #   run: >
      #     curl --output 999999/1603/45/16/1603_45_16.index.hxl.csv
      #     https://raw.githubusercontent.com/EticaAI/lsf-cache/main/999999/1603/45/16/1603_45_16.index.hxl.csv
      #   continue-on-error: true

      # - run: ls -lha 1603/1/99/1603_1_99.no1.tm.hxl.csv
      #   continue-on-error: true

      # - run: ls -lha 999999/1603/45/16/1603_45_16.index.hxl.csv
      #   continue-on-error: true

      # #### Python ______________________________________________________________
      # # @see https://github.com/actions/setup-python
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.9"
      #     cache: "pip"
      # # - run: pip install libhxl hxltm-eticaai openpyxl frictionless csvkit
      # # - run: pip install -r .github/requirements.txt
      # - run: pip install -r ../.github/requirements.txt
      #   continue-on-error: true

      # #### Java Setup __________________________________________________________
      # # @see https://github.com/marketplace/actions/setup-java-jdk
      # - uses: actions/setup-java@v3
      #   with:
      #     distribution: temurin
      #     java-version: 17

      # ### Apache Jena ----------------------------------------------------------
      # # @see https://github.com/foooomio/setup-jena
      # - uses: foooomio/setup-jena@v2
      # - run: sparql --version

      # ### Rapper (tool for work with low level RDF) ----------------------------
      # # @see https://github.com/foooomio/setup-jena
      # - run: apt install -y raptor-utils
      #   continue-on-error: true

      # #### Debug _______________________________________________________________
      # # _[por-Latn] Lista arquivos locais (útil para saber o que fazer upload [por-Latn]_
      # - run: ls -lha
      # # tree-like command for macos, @see https://superuser.com/questions/359723/mac-os-x-equivalent-of-the-ubuntu-tree-command
      # - run: find * -type f

      # - run: hxltmcli --version
      #   continue-on-error: true

      # - run: riot --version
      #   continue-on-error: true

      # - run: frictionless --version
      #   continue-on-error: true

      # - run: rsync --version
      #   continue-on-error: true

      # ### Debug, internal tools from lexicographi-sine-finibus
      # - run: ./999999999/0/1603_1.py --help
      #   continue-on-error: true

      # - run: ./999999999/0/999999999_7200235.py --help
      #   continue-on-error: true

      # - run: ./999999999/0/1603_3_12.py --help
      #   continue-on-error: true

      # #### ssh keys
      # # @see https://github.com/webfactory/ssh-agent
      # # SSH_PRIVATE_KEY__ID_ED25519__GITHUBRUNNER2022

      # # - run: ssh -T git@github.com
      # #   continue-on-error: true

      # # @TODO beyond bare 'git', also configure gh (GitHub CLI) to use the
      # #       machine operator like @eticaaibot, not the human user. See
      # # docs.github.com/pt/actions/using-workflows/using-github-cli-in-workflows

      # ### 1603_16 ----------------------------------------------------------
      # - run: ls -lha 999999/1603/45/16/
      #   continue-on-error: true

      # - run: ls -lha 999999/1603/45/16/1603_45_16.index.hxl.csv
      #   continue-on-error: true

      # - run: ./999999999/999999_1603_16.workflow.sh
      #   continue-on-error: true

      # - run: ./999999999/1603_16.workflow.sh
      #   continue-on-error: true

      - name: git diff --name-only
        id: git_diff_files
        run: git diff --name-only

      - name: git diff --name-only (result)
        run: echo "The selected color is ${{ steps.git_diff_files.outputs }}"

      # @TODO test first if changes are need, then commit it
      - name: commit changes if necessary
        continue-on-error: true
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Automated data update from sources"
          git push

      # Debug part, remove later, START
      - run: pwd
      - run: find * -type f
        continue-on-error: true
      - run: pwd
      - run: git status
        continue-on-error: true
      # # Debug part, remove later, END
